### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by WenjiaWang0312** [Winston-Gu/CooHOI#1]
Dear authors, I appreciate your work very much. Looking forward to run the codes ASAP~ Will you release in this month?
Thank you very much

**Comment by Winston-Gu** [comment]
Yes, no later than Nov 5. We will release the code ASAP, please stay tuned!

**Comment by DeeDive** [comment]
Great work! Looking forward to the code release! :)

**Comment by Moreland-cas** [comment]
Already Nov 5 in UTC+8
