### ISSUE TITLE
When will the source code be released?

### ISSUE THREAD

**Issue by mengchongxi** [Winston-Gu/CooHOI#2]
Hi jiawei, 

Thank you very much for your work, very special

I'm very interested in this project and would like to know if you have plans to open source the code. Do you have a timeline for making the repository public?

Thank you for your time.

**Comment by Winston-Gu** [comment]
Sry for the delay. A little busy these days so the original plan was postponed. I will release all the code by the week of Nov 15. Thanks for your patience🥹

**Comment by MukilSaravanan** [comment]
Hi Winston,

Congratulations on the great work! I'm highly interested in testing out the model by myself to gain insights. 
It would be helpful if it is possible to open-source the codes.

Thanks in advance!

**Comment by Zavianx** [comment]
Hi, When will the code be realsed?
Best wishes

**Comment by Winston-Gu** [comment]
sry for the delay again :( I am too busy with my phd application these days, I plan to open-source the code in the week of Dec 16. Thanks so much for your patience

**Comment by 394262597** [comment]
Hi, I noticed that your latest release information is expected 16th open source. May I ask how the progress is now?

**Comment by Winston-Gu** [comment]
Code open sourced! Thanks for your patience!
